#!/bin/bash
set -e
set -x 

#---
# remove different feature
# fraction_feat=0.1

# # train remove random edge and random feature
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.1 --same_feat False


# # train remove randomwalk
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node 
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node &

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node 
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.1 --same_feat False --feature_to_node  &


# # train remove DummyExplainer (不管有沒有 feature2node，移除的 feature 都是 random)
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.1 --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False



# # train remove GNNExplainer (node_imp)
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False


# train remove GNNExplainer (feat2node)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.1 --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.1 --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.1 --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.1 --same_feat False --feature_to_node


#---
# Start Stage 3 (先固定移除20%邊)
# fraction_feat=0.2

# train remove random edge and random feature
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.2  --same_feat False


# train remove randomwalk
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node &

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.2  --same_feat False --feature_to_node &


# train remove DummyExplainer (不管有沒有 feature2node，移除的 feature 都是 random)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.2  --same_feat False 
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False



# train remove GNNExplainer (node_imp)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False


# train remove GNNExplainer (feat2node)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.2  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.2  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.2  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.2  --same_feat False --feature_to_node


#---
# Start Stage 3 (先固定移除20%邊)
# fraction_feat=0.3

# train remove random edge and random feature
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.3  --same_feat False 
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.3  --same_feat False 
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.3  --same_feat False 


# train remove randomwalk
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node  &

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.3  --same_feat False --feature_to_node  &


# train remove DummyExplainer (不管有沒有 feature2node，移除的 feature 都是 random)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False



# train remove GNNExplainer (node_imp)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False


# train remove GNNExplainer (feat2node)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.3  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.3  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.3  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.3  --same_feat False --feature_to_node


#---
# # Start Stage 3 (先固定移除20%邊)
# # fraction_feat=0.4

# # train remove random edge and random feature
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.4  --same_feat False 
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.4  --same_feat False


# # train remove randomwalk
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node  &

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.4  --same_feat False --feature_to_node  &


# # train remove DummyExplainer (不管有沒有 feature2node，移除的 feature 都是 random)
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False



# # train remove GNNExplainer (node_imp)
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False


# # train remove GNNExplainer (feat2node)
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.4  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.4  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.4  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.4  --same_feat False --feature_to_node


#---
# Start Stage 3 (先固定移除20%邊)
# fraction_feat=0.5

# train remove random edge and random feature
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.5  --same_feat False  
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.5  --same_feat False 
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode baselineResult_difffeat --note difffeat --selector_type random --fraction 0.2 --fraction_feat 0.5  --same_feat False 


# train remove randomwalk
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note random_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose random --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note top_pagerank_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose top_pagerank --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note high_betweenness_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose high_betweenness --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node  &

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node
# python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_RandomWalk_difffeat --note stratified_by_degree_RandomWalk_difffeat --selector_type random_walk --walk_length 50  --fraction 0.2  --node_choose stratified_by_degree --node_ratio auto --edge_ratio 0.3 --fraction_feat 0.5  --same_feat False --feature_to_node  &


# train remove DummyExplainer (不管有沒有 feature2node，移除的 feature 都是 random)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose random --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_DummyExplainer_difffeat --note true_y_DummyExplainer_difffeat --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name DummyExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False



# train remove GNNExplainer (node_imp)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_node_mask --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3 --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False


# train remove GNNExplainer (feat2node)
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose random --fraction_feat 0.5  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose top_pagerank --fraction_feat 0.5  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose high_betweenness --fraction_feat 0.5  --same_feat False --feature_to_node

python train_remaining_main.py --dataset Cora --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset CiteSeer --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False --feature_to_node
python train_remaining_main.py --dataset Amazon --model GCN2 --epochs 300 --lr 0.01 --run_mode remove_from_GNNExplainer_difffeat --note true_y_GNNExplainer_feat2node --selector_type explainer --fraction 0.2 --base_dir saved/stage2_y_edge_0.3_feature2node --explainer_name GNNExplainer --node_choose stratified_by_degree --fraction_feat 0.5  --same_feat False --feature_to_node


wait