#!/bin/bash
set -e
set -x 

# try

# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type random --run_mode try_stage3_random_samefeat --note split0_random_samefeat --fraction_feat 0.1 --same_feat --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2 --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_samefeat --note split0_node_mask_samefeat --fraction_feat 0.1 --same_feat --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_nn_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_samefeat --note split0_feat2node_samefeat_nn_fn --fraction_feat 0.1 --same_feat --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_samefeat --note split0_feat2node_samefeat_fn --fraction_feat 0.1 --same_feat --feature_to_node --only_feature_node --stage1_path saved/stage1_feature2node_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type random --run_mode try_stage3_random_difffeat --note split0_random_difffeat --fraction_feat 0.1 --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2 --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_difffeat --note split0_node_mask_difffeat --fraction_feat 0.1 --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_nn_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_difffeat --note split0_feat2node_difffeat_nn_fn --fraction_feat 0.1 --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_difffeat --note split0_feat2node_difffeat_fn --fraction_feat 0.1 --feature_to_node --only_feature_node --stage1_path saved/stage1_feature2node_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type random --fraction 0.1 --run_mode try_stage3_random_samefeat --note split0_random_samefeat_edge --fraction_feat 0.1 --same_feat --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2 --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_samefeat_edge --note split0_node_mask_samefeat_edge --fraction_feat 0.1 --same_feat --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2_feature2node_nn_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_samefeat_edge --note split0_feat2node_samefeat_edge_nn_fn --fraction_feat 0.1 --same_feat --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type random --fraction 0.1 --run_mode try_stage3_random_difffeat_edge --note split0_random_difffeat_edge --fraction_feat 0.1 --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2 --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_difffeat_edge --note split0_node_mask_difffeat_edge --fraction_feat 0.1 --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2_feature2node_nn_fn --explainer_name GNNExplainer --node_choose pagerank --run_mode try_stage3_GNNExplainer_difffeat_edge --note split0_feat2node_difffeat_edge_nn_fn --fraction_feat 0.1 --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2 --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_edge --note split0_cf_edge --stage1_path saved/stage1
# python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.3 --base_dir saved/stage2 --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_edge --note split0_cf_edge --stage1_path saved/stage1
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_nn_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_samefeat --note split0_feat2node_samefeat_nn_fn --fraction_feat 0.1 --same_feat --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_samefeat --note split0_feat2node_samefeat_fn --fraction_feat 0.1 --same_feat --feature_to_node --only_feature_node --stage1_path saved/stage1_feature2node_fn
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_nn_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_difffeat --note split0_feat2node_difffeat_nn_fn --fraction_feat 0.1 --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --base_dir saved/stage2_feature2node_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_difffeat --note split0_feat2node_difffeat_fn --fraction_feat 0.1 --feature_to_node --only_feature_node --stage1_path saved/stage1_feature2node_fn
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2_feature2node_nn_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_samefeat_edge --note split0_feat2node_samefeat_edge_nn_fn --fraction_feat 0.1 --same_feat --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn
python train_remaining_main.py --dataset Cora --model GCN2 --epochs 1 --lr 0.01 --selector_type explainer --fraction 0.1 --base_dir saved/stage2_feature2node_nn_fn --explainer_name CFExplainer --node_choose all_train --run_mode try_stage3_CFExplainer_difffeat_edge --note split0_feat2node_difffeat_edge_nn_fn --fraction_feat 0.1 --feature_to_node --stage1_path saved/stage1_feature2node_nn_fn

# 
wait